[package]
name = "quark_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.15.0", features = ["macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
log = "0.4"
tracing-subscriber = "0.3"
dotenvy = "0.15"
sled = "0.34.7"
contracts = { path = "../contracts" }
quark_backend = { path = "../quark_backend" }
