version: '3.8'

services:
  quark-server:
    container_name: quark-server
    build:
      context: .
      dockerfile: quark_server/Dockerfile
    ports:
      - "3200:3200"
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - APTOS_NETWORK=${APTOS_NETWORK}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - TOKEN_PAYMENT_ADDRESS=${TOKEN_PAYMENT_ADDRESS}
      - SECRET=${SECRET}
      - GPG_PASSPHRASE=${GPG_PASSPHRASE}
      - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
      - GPG_PUBLIC_KEY=${GPG_PUBLIC_KEY}
      - GPG_REVIEWER=${GPG_REVIEWER}
    networks:
      - quark-net

  quark-bot:
    container_name: quark-bot
    build:
      context: .
      dockerfile: quark_bot/Dockerfile
    depends_on:
      - quark-server
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STORAGE_CREDENTIALS=${STORAGE_CREDENTIALS}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - APTOS_NETWORK=${APTOS_NETWORK}
      - PANORA_URL=${PANORA_URL}
      - PANORA_API_KEY=${PANORA_API_KEY}
      - TIME_API_BASE_URL=${TIME_API_BASE_URL}
      - SLED_URL=${SLED_URL}
      - SECRET=${SECRET}
      - APP_URL=${APP_URL}
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - quark-net
    volumes:
      - quark-data:/app/quark_data

  quark-webhook:
    build:
      context: .
      dockerfile: quark-webhook/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_EXPLORER_URL=${NEXT_PUBLIC_EXPLORER_URL}
      - ACCOUNT_SEED=${ACCOUNT_SEED}
      - APTOS_NODE_URL=${APTOS_NODE_URL}
      - APTOS_INDEXER=${APTOS_INDEXER}
      - NEXT_PUBLIC_APTOS_NETWORK=${NEXT_PUBLIC_APTOS_NETWORK}
    networks:
      - quark-net

volumes:
  quark-data:

networks:
  quark-net:
    driver: bridge 