[package]
name = "quark_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
open-ai-rust-responses-by-sshift = "0.1.8"
sled = "0.34.7"
bincode = "1.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
contracts = { path = "../contracts" }
