name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Prepare template sources (if needed)
        shell: bash
        run: |
          set -euo pipefail
          # Copy AI template files to expected module names if the real files are absent
          if [[ -f quark_bot/src/ai/prompt_template.rs && ! -f quark_bot/src/ai/prompt.rs ]]; then
            cp quark_bot/src/ai/prompt_template.rs quark_bot/src/ai/prompt.rs
          fi
          if [[ -f quark_bot/src/ai/moderation/moderation_service_template.rs && ! -f quark_bot/src/ai/moderation/moderation_service.rs ]]; then
            cp quark_bot/src/ai/moderation/moderation_service_template.rs quark_bot/src/ai/moderation/moderation_service.rs
          fi
          if [[ -f quark_bot/src/ai/moderation/overrides_template.rs && ! -f quark_bot/src/ai/moderation/overrides.rs ]]; then
            cp quark_bot/src/ai/moderation/overrides_template.rs quark_bot/src/ai/moderation/overrides.rs
          fi
          if [[ -f quark_bot/src/ai/schedule_guard/schedule_guard_service_template.rs && ! -f quark_bot/src/ai/schedule_guard/schedule_guard_service.rs ]]; then
            cp quark_bot/src/ai/schedule_guard/schedule_guard_service_template.rs quark_bot/src/ai/schedule_guard/schedule_guard_service.rs
          fi

      - name: Cargo check (workspace)
        run: cargo check --workspace

      - name: Run unit tests for quark_bot
        run: cargo test -p quark_bot --lib

      - name: Grep for direct HTML sends (informational)
        run: |
          echo "Listing .parse_mode(ParseMode::Html) occurrences in quark_bot/src (informational):"
          if command -v rg >/dev/null 2>&1; then
            rg -n "\\.parse_mode\\(ParseMode::Html\\)" quark_bot/src || true
          else
            grep -RIn "\\.parse_mode(ParseMode::Html)" quark_bot/src || true
          fi
